spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pluv_relacional
    username: postgres
    password: root123
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: public
    open-in-view: false

  data:
    mongodb:
      uri: none

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
      - org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration